services:
  - type: web
    name: parkway-backend
    env: java
    plan: free
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -Dserver.port=$PORT -jar target/*.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: FRONTEND_URL
        value: https://parkway-frontend.onrender.com
      - key: SPRING_DATASOURCE_URL
        value: ${DATABASE_URL}
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres.jlwfkrzsqamopqjkzbtd
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: supabase-db
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
